{
  flake.modules.nixos.kubernetes-compute =
    {
      pkgs,
      config,
      lib,
      clanLib ? null,
      roles ? { },
      ...
    }:
    let
      generators = config.clan.core.vars.generators;
      clusterName = config.nut.kubernetes.instanceName;
      nodeIP = config.nut.kubernetes.nodeIP;
      hostname = config.networking.hostName;
      clusterDomain = config.nut.kubernetes.domain;
      serviceCIDR = config.nut.kubernetes.serviceCIDR;

      # Calculate DNS IP from service CIDR (10th IP in the CIDR range)
      # For IPv6 CIDR like "fd00:10:97::/108", the DNS IP is typically the 10th address (0xa in hex)
      calculateDNSIP =
        cidr:
        let
          parts = lib.splitString "/" cidr;
          baseAddr = lib.head parts;
          cleanAddr = lib.removeSuffix "]" (lib.removePrefix "[" baseAddr);
          dnsIP = lib.replaceStrings [ "::" ] [ "::a" ] cleanAddr;
        in
        dnsIP;

      clusterDNS = calculateDNSIP serviceCIDR;

      # Get API server endpoint:
      # 1. Use configured option (which defaults to service-level setting)
      # 2. Auto-detect from first controller node via clanLib
      # 3. Fallback to local node IP (for control-plane nodes that also run kubelet)
      apiServerEndpoint =
        if config.nut.kubernetes.apiServerEndpoint != null then
          config.nut.kubernetes.apiServerEndpoint
        else if clanLib != null && (roles.controller.machines or { }) != { } then
          let
            controllerMachineNames = builtins.attrNames roles.controller.machines;
            firstController = lib.head controllerMachineNames;
            getZerotierIp =
              machineName:
              clanLib.getPublicValue {
                flake = config.clan.core.settings.directory;
                machine = machineName;
                generator = "zerotier";
                file = "zerotier-ip";
              };
          in
          "https://[${getZerotierIp firstController}]:6443"
        else
          "https://[${nodeIP}]:6443"; # Fallback to local node IP (for control-plane nodes that also run kubelet)
    in
    {
      environment.systemPackages = [ pkgs.kubernetes ];

      # Enable containerd for container runtime
      virtualisation.containerd.enable = true;

      # Enable IPv6 forwarding for pod networking (required even without CNI for now)
      boot.kernel.sysctl = {
        "net.ipv6.conf.all.forwarding" = 1;
      };

      # Generate kubelet kubeconfig
      clan.core.vars.generators = {
        kubernetes-kubelet-kubeconfig = {
          share = false;
          files."kubelet.kubeconfig" = {
            secret = true;
            owner = "kubernetes";
            group = "kubernetes";
            mode = "0440";
          };
          dependencies = [
            "kubernetes-ca-crt"
            "kubernetes-kubelet-client-crt"
          ];
          runtimeInputs = [ pkgs.kubectl ];
          script = ''
            kubectl config set-cluster ${clusterName} \
              --certificate-authority=$in/kubernetes-ca-crt/ca.crt \
              --embed-certs=true \
              --server=${apiServerEndpoint} \
              --kubeconfig=$out/kubelet.kubeconfig

            kubectl config set-credentials system:node:${hostname} \
              --client-certificate=$in/kubernetes-kubelet-client-crt/kubelet-client.crt \
              --client-key=$in/kubernetes-kubelet-client-crt/kubelet-client.key \
              --embed-certs=true \
              --kubeconfig=$out/kubelet.kubeconfig

            kubectl config set-context default \
              --cluster=${clusterName} \
              --user=system:node:${hostname} \
              --kubeconfig=$out/kubelet.kubeconfig

            kubectl config use-context default \
              --kubeconfig=$out/kubelet.kubeconfig
          '';
        };
      };

      # Kubelet configuration file
      # Using static certificates with rotateCertificates for auto-renewal
      environment.etc."kubernetes/config/kubelet-config.yaml".text = ''
        apiVersion: kubelet.config.k8s.io/v1beta1
        kind: KubeletConfiguration
        authentication:
          x509:
            clientCAFile: "/var/lib/kubelet/ca.crt"
        authorization:
          mode: Webhook
        clusterDomain: "${clusterDomain}"
        clusterDNS:
          - "${clusterDNS}"
        cgroupDriver: "systemd"
        failSwapOn: false
        serializeImagePulls: false
        # Static TLS certificates (generated by clan vars)
        tlsCertFile: "/var/lib/kubelet/kubelet-server.crt"
        tlsPrivateKeyFile: "/var/lib/kubelet/kubelet-server.key"
        # Enable certificate rotation for client certs (kubelet will request renewal before expiry)
        rotateCertificates: true
        evictionHard:
          memory.available: "200Mi"
          nodefs.available: "10%"
          nodefs.inodesFree: "5%"
        evictionSoft:
          memory.available: "200Mi"
        evictionSoftGracePeriod:
          memory.available: "1m"
        evictionMaxPodGracePeriod: 30
        evictionPressureTransitionPeriod: "30s"
        tlsCipherSuites:
          - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
          - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
          - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305"
          - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
          - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
          - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
      '';

      # Symlink kubelet kubeconfig
      systemd.tmpfiles.rules = [
        "L+ /var/lib/kubelet/kubelet.kubeconfig - - - - ${
          generators.kubernetes-kubelet-kubeconfig.files."kubelet.kubeconfig".path
        }"
      ];

      # Kubelet systemd service
      # Kubelet runs as root because it needs to manage containers, networking, volumes, and cgroups
      systemd.services."kubelet" = {
        description = "Kubernetes Kubelet";
        documentation = [ "https://github.com/kubernetes/kubernetes" ];
        wantedBy = [ "kubernetes.target" ];
        after = [
          "network.target"
          "containerd.service"
        ];
        requires = [ "containerd.service" ];

        serviceConfig = {
          ExecStart = ''
            ${pkgs.kubernetes}/bin/kubelet \
              --config=/etc/kubernetes/config/kubelet-config.yaml \
              --kubeconfig=/var/lib/kubelet/kubelet.kubeconfig \
              --cert-dir=/var/lib/kubelet/pki \
              --container-runtime-endpoint=unix:///run/containerd/containerd.sock \
              --node-ip=${nodeIP} \
              --pod-infra-container-image=registry.k8s.io/pause:3.9 \
              --register-node=true \
              --v=2
          '';
          Restart = "on-failure";
          RestartSec = 5;
          # Kubelet requires root privileges for container management, networking, and cgroups
        };
      };
    };
}
